[book]
title = "Young Lazy deadhead"
description = "Way more than anyone wants to know about Cliff Matthews"
authors = ["Clifford T. Matthews"]
language = "en"
multilingual = false
src = "src"

[rust]
edition = "2021"

[output.html]
no-section-label = true
